### ISSUE TITLE
Incorrect file format

### ISSUE THREAD

**Issue by navierula** [SheepOrange/intro-data-capstone-musclehub#1]
Hi! You seem to have uploaded your solution in a `.py` file. Can you upload it as a `.ipynb` file instead? Your work is a Jupyter Notebook, so it should be uploaded in that format. I'll get back to reviewing your work then!

**Comment by SheepOrange** [comment]
Hi! I have submitted the `.ipynb` file. Just remind that the second requirement of task 4 ask me to change the jupyter notebook file to `.py` file.

> 
>Task 4: Submit Your Project
>1. Save your presentation as a PDF using save as.
>2. Save your iPython notebook as a “.py” file using File > Download as > Python (.py)
>3. If you created a video, create a file called video.txt with a link to the video
>4. Move your PDF, your Python file, and (optionally) your video.txt into the same folder.
>5. Upload the folder to Codecademy!
>

**Comment by navierula** [comment]
Thanks for referencing this! The `.py` file would've been fine if it didn't contain the Jupyter notebook markup language. Thanks for uploading a new file!
